name: Test Docker Build

on:
  pull_request:
    branches: ['main']
    paths:
      - 'Dockerfile'
      - '.github/workflows/test-build.yaml'

jobs:
  test-build:
    name: Test Docker Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Test multi-platform build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and load image for testing
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: podman-ci-toolkit:test

      - name: Test image
        run: |
          echo "Running basic tests on the built image..."
          
          # Test that the image runs
          docker run --rm podman-ci-toolkit:test sh -c "echo 'Container started successfully'"
          
          # Test that all tools are available
          echo "Testing tool availability..."
          
          # Test specific tools
            
          docker run --rm podman-ci-toolkit:test jq --version
          
          echo -e "\nTesting Make..."
          docker run --rm podman-ci-toolkit:test make --version
          
          echo -e "\nTesting Bash..."
          docker run --rm podman-ci-toolkit:test bash --version
          
          echo -e "\nTesting Crane..."
          docker run --rm podman-ci-toolkit:test crane version
          
          echo -e "\nTesting Vault..."
          docker run --rm podman-ci-toolkit:test vault version
          
          echo -e "\nTesting Manifest-Tool..."
          docker run --rm podman-ci-toolkit:test manifest-tool --version
          
          echo -e "\nTesting Cosign..."
          docker run --rm podman-ci-toolkit:test cosign version
          
          echo -e "\nTesting Oras..."
          docker run --rm podman-ci-toolkit:test oras version
          
          echo -e "\nTesting Podman executor..."
          docker run --rm podman-ci-toolkit:test podman --version
          
          echo -e "\nTesting Buildah executor..."
          docker run --rm podman-ci-toolkit:test buildah --version

          echo -e "\nAll tests passed!"
